<div class="section section-1 box-wapper-show-image">
	<div class="container">
		<ol class="breadcrumb" style="padding-bottom: 0;margin-bottom: 0;">
			<li><a href="<?php echo base_url();?>">Home</a></li>
			<li><?php echo $title_page; ?></li>
		</ol>
		<h1>ONLINE ADVERTISING AGREEMENT</h1>
		<article class="article">
			<p>TERMS OF USE AGREEMENT</p>
			<p>Welcome to the dezignwall website. This Terms of Use Agreement ("Agreement") constitutes a legally binding contract between dezignwall, Inc., a Delaware corporation ("dezignwall," "we," "us," "our") and you with respect to your use of the dezignwall website, dezignwall applications for mobile devices, and the Information and Services (each as defined below) (collectively, the "Website"). It is important that you carefully read and understand the terms and conditions of this Agreement. By using the Website, you agree to be bound by this Agreement. If you do not agree to these terms and conditions, please do not use the Website or any of the Information or Services. Be advised that this Agreement contains disclaimers of warranties and limitations on liability that may be applicable to you.</p>
			<p><strong>We reserve the right at any time, with or without cause, to:</strong></p>

			<ul class="disc">
				<li>change the terms and conditions of this Agreement;</li>
				<li>change the Website, including eliminating or discontinuing any Information or Services or other feature of the Website; or</li>
				<li>deny or terminate your use of and/or access to the Website.</li>
			</ul>

			<p>Any changes we make will be effective immediately upon our making such changes available on the Website or otherwise providing notice thereof. You agree that your continued use of the Website after such changes constitutes your acceptance of such changes. You hereby acknowledge that you have carefully read all of the terms and conditions of our Privacy Policy (which can be accessed at http://dezignwall.com/privacypolicy) and agree to all such terms and conditions. Be sure to return to this page periodically to ensure familiarity with the most current version of this Agreement.</p>
			<p><strong>Permitted Use of Services and Information</strong></p>
			<p>The services made available on, by or through the Website, which include or may include, without limitation, dezignwall registration, marketplace for third-party products and services, Design Walls, message boards and involvement in dezignwall events (collectively, the "Services"), as well as any information provided on, by or through the Website or as part of or in connection with the Services or otherwise, including but not limited to data, text, graphics, designs, logos, images, audio/visual materials, links and references (collectively, the "Information"), are provided for personal use only and not for any for-profit or commercial activities or purpose or for resale, except as expressly permitted herein. Without the written consent of dezignwall, no Information or any other dezignwall materials or property may be copied, reproduced, displayed, republished, downloaded, posted, digitized, translated, modified, transmitted, distributed or commercially exploited in any way, except as expressly permitted herein.</p>
			<p>dezignwall permits you to view and print a reasonable number of copies of web pages located on the Website for your own personal use, but not for any for-profit or commercial purpose or for resale; provided that (a) you retain all trademark, copyright, and other proprietary notices contained in the original materials, (b) you provide attribution to dezignwall, (c) the material is printed in its entirety without modification, reformatting or adaptation of any kind, and (d) any such copies are subject to the terms and conditions of this Agreement and remain the property of dezignwall. You understand and agree that you may not authorize any Information to be reproduced, modified, displayed, performed, transferred, distributed or otherwise used by any third party, and you agree that you will take all reasonable steps to prevent any unauthorized reproduction and/or other use of the Information. You agree to advise dezignwall promptly of any such unauthorized use of which you are aware. Failure to abide by these conditions will immediately terminate this permission and may result in the infringement of the copyrights and/or trademarks and other proprietary rights of dezignwall or others.</p>
			<p><strong>Registration</strong></p>
			<p>Access to certain functionalities of the Website will require you to register with and/or provide certain information to dezignwall. We reserve the right to decline to provide Services to any person for any or no reason. If and when you register with or provide information to dezignwall, you agree to (a) provide accurate, current and complete information about yourself as prompted (including your email address) and (b) maintain and update your information (including your email address) to keep it accurate, current and complete. You acknowledge that, if any information provided by you is untrue, inaccurate, not current or incomplete, we reserve the right to terminate this Agreement and your use of the Website, Services, and/or Information. You understand that any information you provide will be treated by dezignwall in the manner described in our Privacy Policy, which can be found at http://www.dezignwall.com/privacypolicy.</p>
			<p><strong>Professional Accounts</strong></p>
			<p>Advertising clients may elect to register with dezignwall as a Preferred Member and create a Advertising profile on dezignwall. Subject to and conditioned on compliance with all of the terms of this Agreement, such users are permitted to use the Advertising account/profile features offered by dezignwall to promote their business. All such dezignwall Adevertising features are subject to discontinuance or change at any time. All of the terms and conditions of this Agreement apply to your use of any such professional account and profile, including without limitation, maintaining profile information, uploading or other posting of Content, posting of Reviews, use of dezignwall buttons, links and widgets, and indemnification obligations.</p>
			<p><strong>Postings and Other Submissions</strong></p>
			<p>As part of your use of the Website, you may participate in certain Design Walls, message boards, member communications and/or other public forums. Your participation is voluntary; however, by choosing to create Design Walls, post photos or comments, send any messages, submit any ideas or feedback, or otherwise participate in any dezignwall forum, you acknowledge and agree that any postings, messages, text, photos, audio/visual works, information, suggestions, feedback, reviews or content provided by you (collectively, "Content") may be viewed by the general public and will not be treated as private, proprietary or confidential, and you authorize us and our affiliates, licensees and sublicensees, without compensation to you or others, to copy, adapt, create derivative works of, reproduce, incorporate, distribute, publicly display or otherwise use or exploit such Content throughout the world in any format or media (whether now known or hereafter created) for the duration of any copyright or other rights in such Content, and such permission shall be perpetual and may not be revoked for any reason. Further, to the extent permitted under applicable law, you waive and release and covenant not to assert any moral rights that you may have in any Content posted or provided by you.</p>
			<p>dezignwall acknowledges and agrees that you, or your licensors as applicable, retain ownership of any and all copyrights in the Content, subject to the non-exclusive rights granted to dezignwall in the paragraph above, and that no ownership of such copyrights is transferred to dezignwall under these terms. Further, with respect to Content in the form of photos, and subject to dezignwall product and user experience considerations (a) dezignwall will use commercially reasonable efforts to maintain the attribution of such photos as submitted by you, and (b) dezignwall will not license or sublicense to third parties individual photo Content or collections of photo Content submitted by you, except in each case for dezignwall Business Purposes. “dezignwall Business Purposes” means any use in connection with a dezignwall-branded or co-branded website, application, publication or service, or any use which advertises, markets or promotes dezignwall, or its affiliates.</p>
			<p>By posting or providing any Content on the Website, you represent and warrant to dezignwall that you own or have the right to use and permit us to use and license such Content in the manner stated in this Agreement. By way of example and not limitation, if you post or otherwise provide a photograph which includes an image of any person, you need to first obtain permission or a release from such person appearing in the photograph to use their image and permit us to use and license it as stated in this Agreement and you must be the owner or licensee of the copyright in the photograph, with the right to permit us to use it as stated in this Agreement. By way of further example and not limitation, if you post or otherwise provide a photograph of a pictorial, graphic, sculptural or architectural work that is protected by copyright, you need to first obtain permission or a release from the owner of the copyright in such work to reproduce and adapt their work and permit us to use it as stated in this Agreement and you must be the owner or licensee of the copyright in the photograph, with the right to permit us to use it as stated in this Agreement.</p>
			<p>dezignwall may enable you to post ratings or reviews of vendors, service providers and/or their products or services on the Website (your “Reviews”). Reviews are considered Content. You may not post any reviews about a vendor, service provider or any of their products or services if you are (a) an employee, contractor, officer or director of the vendor and/or service provider; (b) an employee, contractor, officer or director of a competitor of the vendor and/or service provider; or (c) related to the vendor and/or service provider in any way, including blood, adoption or by marriage. By posting a Review, you acknowledge and agree that such Content:</p>
			<p>(1) is based upon your first-hand experience with the vendor, service provider or product or service that is the subject of the Review;</p>
			<p>(2) is accurate, truthful and complete.</p>
			<p>You agree not to post or provide any Content that belongs to any person other than yourself or that contains the name, voice or likeness of any person other than yourself unless you first obtain permission to do so, and to grant to us the rights granted in this agreement, from that person.</p>
			<p>If you identify yourself by name or provide a picture or audio or video recording of yourself, you further authorize us and our affiliates, licensees and sublicensees, without compensation to you or others, to reproduce, print, publish and disseminate in any format or media (whether now know or hereafter created) your name, voice and likeness throughout the world, and such permission shall be perpetual and cannot be revoked for any reason.</p>
			<p>You further agree that we may use the posted or provided Content in any manner that we deem appropriate or necessary. We reserve the right to edit or abridge any Content for any reason, and to edit, refuse to post or remove any Content submitted by you or others. We cannot and do not guarantee that we will post all Content submitted or that such content will not be offensive, defamatory or objectionable. Although we reserve the right to remove without notice any Content for any reason, we have no obligation to delete Content that you personally may find objectionable or offensive. We do not control in real time the Content posted via the Services and as such do not guarantee the accuracy, integrity or quality of such Content. In addition to other disclaimers found in this Agreement, we do not endorse or make any warranties or representations with respect to the accuracy, completeness or timeliness of any Content posted on the Website.</p>
			<p><strong>Third-Party Links</strong></p>
			<p>The Website may contain links to other websites for your convenience. We do not control the linked websites or the content provided through such websites, and we have not reviewed, in their entirety, such websites. Your use of linked websites is subject to the privacy practices and terms of use established by the specific linked website, and we disclaim all liability for such use. The fact that we offer such links does not indicate any approval or endorsement by us of any linked website or any material contained on any linked website, and we disclaim any such approval or endorsement.</p>
			<p><strong>Third-Party Products and Services</strong></p>
			<p>You may be provided the opportunity to purchase products and services offered and sold by third parties (“Products”) through the Services. The information provided for any Product listing is provided by dezignwall’s third-party vendors, and, while we require vendors to provide complete, accurate and non- misleading Product information, we do not represent, warrant or guarantee that such Product descriptions are accurate, complete, reliable, current, or error-free, and we are not responsible for, and disclaim any liability arising from or relating to, such Product listing information. All purchases of Products made by you through the Services are a direct sale and purchase between you and the applicable vendor. dezignwall is not a party to such transaction, and only facilitates the transaction between you and the vendor by providing a marketplace for the marketing, offering and sale of Products. Payments for Products transacted through the Service will be remitted to the vendor, and the vendor will be solely responsible for fulfilling and shipping your order, providing related customer support and warranty service and processing returns and exchanges. The Services will facilitate your communication with the vendor for the purpose of making return, exchange or warranty requests or making claims for non-delivery, damaged goods or items not as described in accordance with any applicable terms or policies in the Product listing. In addition, the Services may alert you to any Product issues or recalls of which the vendor notifies dezignwall. dezignwall does not provide any warranty on any of the Products, whether express or implied, and does not assume, and hereby disclaims, any responsibility or liability for the actions or inactions of the third-party vendors of such Products, or for the Products offered, sold or provided by, any third party through the Service.</p>
			<p>Descriptions or images of, or references to, third-party Products or publications on the Website do not imply our endorsement of such Products and publications, and we are not responsible for, and disclaim any endorsement of, any such Product or publication.</p>
			<p>Reviews are solely the opinions of the users that post them and none of the Reviews contain or reflect any opinions or views of dezignwall.</p>
			<p><strong>Acceptable Use Policy</strong></p>
			<p>You agree not to use the Information, Services or the Website to take any action or actions that:</p>
			<p>a) are contrary to dezignwall's public image, goodwill or reputation;</p>
			<p>b) infringe on our or any third party's copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy;</p>
			<p>c) express or imply that any of your statements, activities or causes are endorsed by us, without our prior written consent in each instance;</p>
			<p>d) violate any applicable law, statute, ordinance or regulation, or encourage any conduct that could constitute a criminal offense or give rise to civil liability;</p>
			<p>e) are libelous, defamatory, threatening, harassing, invasive of privacy, abusive, tortious, hateful, discriminatory, pornographic or obscene;</p>
			<p>f) transmit any trade secret or other material, non-public information about any person, company or entity without the authorization to do so;</p>
			<p>g) restrict or inhibit any other visitor from using the Website, including, without limitation, by means of "hacking" or defacing any portion of the Website;</p>
			<p>h) modify, adapt, sub-license, translate, sell, reverse engineer, decompile, or disassemble any portion of the Website or Information;</p>
			<p>i) remove any copyright, trademark, or other proprietary rights notices contained in or on the Information, Website, or Services;</p>
			<p>j) sublicense, sell, rent, lease, transfer, assign, or convey any rights under this Agreement to any third party, or otherwise commercially exploit or profit from the Information or content of the Website, or any portion thereof, in any manner whatsoever, except as expressly permitted herein;</p>
			<p>k) "frame" or "mirror" any part of the Website without our prior written authorization;</p>
			<p>l) distribute any virus, worm or other similar or deleterious files, scripts or programming routines;</p>
			<p>m) interfere with or disrupt any services or equipment with the intent of causing an excessive or disproportionate load on the infrastructure of dezignwall or its licensors or suppliers;</p>
			<p>n) involve the preparation or distribution of junk mail, spam, chain letters, pyramid schemes, or other deceptive or unsolicited bulk or commercial email, or violate in any way the Controlling the Assault of Non-Solicited Pornography and Marketing Act (CAN-SPAM Act of 2003);</p>
			<p>o) use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, "data mine" the Website or in any way reproduce or circumvent the navigational structure or presentation of the Website or its contents, authentication and security measures;</p>
			<p>p) forge headers or otherwise manipulate identifiers in order to disguise the origin of any submission;</p>
			<p>q) execute any form of network monitoring or run a network analyzer or packet sniffer or other technology to intercept, decode, mine or display any packets used to communicate between the Website's servers or any data not intended for you; and/or</p>
			<p>r) harvest or collect information about any Website visitors or members without their express consent.</p>
			<p>Improper use of the Information, Services and Website may result in termination of your access to and use of the Website, and/or civil or criminal liabilities.</p>
			<p><strong>Ownership</strong></p>
			<p>The Website is owned and operated by dezignwall and its licensors, and the Information and Services (and any intellectual property and other rights relating thereto) are and will remain the property of dezignwall and its licensors and suppliers. The Information and Services are protected by U.S. and international copyright, trademark, and other laws, and you acknowledge that these rights are valid and enforceable. Except as set forth in this Agreement, you may not copy, reproduce, modify, adapt, translate, republish, upload, post, transmit, distribute, sub-license, sell, reverse engineer, decompile, or disassemble any part of the Website or any Service or Information without our prior written permission. The Information, Website, and Services may be used solely (a) to the extent permitted in this Agreement or (b) as expressly authorized in writing by dezignwall or, if so indicated in writing by dezignwall, its licensors or suppliers. Use of the Website or any Services or Information for any other purpose is strictly prohibited. You acknowledge that you do not acquire any ownership rights by using the Website or any Services or Information.</p>
			<p>The trademarks, logos, and service marks displayed on the Website (collectively, the "Trademarks") are the registered and unregistered trademarks of dezignwall, dezignwall licensors and suppliers, and/or others. dezignwall® is a registered trademark of dezignwall, Inc. Nothing contained in this Agreement or the Website should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark(s) without the express written permission of dezignwall, dezignwall licensors or suppliers, or the third party owner of any such Trademark, except as set forth in the following paragraph.</p>
			<p><strong>dezignwall Buttons, Links and Widgets</strong></p>
			<p>You may use the dezignwall buttons, links and widgets displayed on the 'Buttons and Badges' section of this Website provided that (a) such buttons, links and widgets link only to the Website; (b) you do not modify such buttons, links, widgets or associated code in any manner, (c) you do not use any such buttons, links, widgets in any manner which implies or suggests that dezignwall operates, endorses, sponsors or recommends the website on which such buttons, links and widgets are used, and (d) the use of such buttons, links and widgets, and the website on which such buttons, links and widgets are used do not violate the dezignwall acceptable use policy stated above. You acknowledge and agree that all rights in and to the dezignwall trademarks are our exclusive property, and any goodwill generated by your use of any dezignwall trademark will inure to our exclusive benefit. You will not take any action that is in conflict with our rights in or ownership of any dezignwall trademark. We retain the right to revoke the permission to use such buttons, links and widgets at any time for any reason.</p>
			<p><strong>No Use by Children Under 13</strong></p>
			<p>You hereby affirm that you are over the age of 12, as this Website is not intended for children under 13. If you are under 13 years of age, then you may not use the Website. You further affirm that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in this Agreement, and to abide by and comply with this Agreement.</p>
			<p><strong>Claims of Copyright or Trademark Infringement</strong></p>
			<p>The Digital Millennium Copyright Act (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. dezignwall also reviews claims of trademark infringement. If you believe in good faith that materials hosted by dezignwall infringe your copyright or trademark rights, you (or your agent) may send us a notice requesting that the material be removed, or access to it blocked. The notice must include the following information: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (b) identification of the copyrighted work or trademark claimed to have been infringed (or if multiple copyrighted works or trademarks located on the Website are covered by a single notification, a representative list of such works); (c) identification of the material that is claimed to be infringing or the subject of infringing activity, and information reasonably sufficient to allow dezignwall to locate the material on the Website; (d) the name, address, telephone number, and email address (if available) of the complaining party; (e) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright or trademark owner, its agent, or the law; and (f) a statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. Please be advised that dezignwall will not respond to complaints that do not meet these requirements. If dezignwall determines that the materials alleged to infringe your copyright or trademark rights do not require removal, dezignwall will remove those materials only pursuant to a court order declaring the content or use of the materials unlawful.</p>
			<p>If you believe in good faith that a notice of copyright infringement has been wrongly filed against you, the DMCA permits you to send us a counter-notice. Counter-notices must include the following information: (a) your name, address, and telephone number; (b) the source of the content that was removed; (c) a statement under penalty of perjury that you have a good faith belief that the content was removed in error; (d) a statement that you consent to the jurisdiction of Federal District Court for the judicial district in which your address is located, or if your address is outside of the United States, for any judicial district in which dezignwall may be found, and that you will accept service of process from the person who provided the original complaint; and (e) a physical or electronic signature (for example, typing your full name).</p>
			<p>Notices and counter-notices with respect to the Website must meet the then-current statutory requirements imposed by the DMCA (see http://www.loc.gov/copyright for details) and should be sent to the agent identified below. We suggest that you consult your legal advisor before filing a notice or counter-notice. Also, be aware that there can be penalties for false claims under the DMCA.</p>
			<p>Agent to Receive Notices of Claimed Infringement</p>
			<p>info@dezignwall.com<br>Complaints<br>dezignwall, Inc.<br>1621 Alton Pkwy #250<br>Irvine CA 92606<br>(949) 988-0604</p>
			<p><strong>Term &amp; Termination</strong></p>
			<p>This Agreement is effective from the date that you first access the Website or submit any information to dezignwall, whichever is earlier, and shall remain effective until terminated in accordance with its terms. dezignwall may immediately terminate this Agreement, and/or your access to and use of the Website, or any portion thereof, at any time and for any reason, with or without cause, without prior notice. This Agreement will also terminate automatically if you fail to comply with any term or provision of this Agreement. Upon termination of this Agreement by either party, your right to use the Website shall immediately cease, and you shall destroy all copies of information that you have obtained from the Website, whether made under the terms of this Agreement or otherwise. All disclaimers and all limitations of liability and all dezignwall rights of ownership shall survive any termination.</p>
			<p>We reserve the right at any time and from time to time to modify, discontinue, temporarily or permanently, the Website, or any part or portion thereof, with or without notice to you. You agree that we shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Website, or any part of portion thereof. Nothing in this Agreement shall be construed to obligate dezignwall to maintain and support the Website, or any part or portion thereof, during the term of this Agreement.</p>
			<p><strong>Disclaimers</strong></p>
			<p>THE WEBSITE, INCLUDING BUT NOT LIMITED TO THE INFORMATION AND SERVICES, ARE PROVIDED "AS IS" AND "WITH ALL FAULTS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE, AND ANY WARRANTIES THAT THE INFORMATION AND WEBSITE IS CURRENT AND/OR UP-TO-DATE ARE HEREBY EXPRESSLY DISCLAIMED TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW.</p>
			<p>THERE IS NO WARRANTY, REPRESENTATION OR GUARANTEE THAT THE WEBSITE, OR YOUR USE OF THE WEBSITE, WILL BE UNINTERRUPTED, COMPLETE, ACCURATE, CURRENT, RELIABLE, ERROR-FREE, SECURE, OR THAT ANY PROBLEMS WILL BE CORRECTED, OR THAT THE WEBSITE, OR ANY INFORMATION, SOFTWARE OR OTHER MATERIAL ACCESSIBLE FROM THE WEBSITE, IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT WARRANT, GUARANTEE, OR MAKE ANY REPRESENTATION REGARDING THE USE OF, OR THE RESULTS OF THE USE OF THE WEBSITE EITHER IN TERMS OF ITS COMPATIBILITY WITH HARDWARE OR OTHER SOFTWARE OR EQUIPMENT, AND YOU ASSUME ALL RESPONSIBILITY AND RISK FOR YOUR USE OF THE WEBSITE AND/OR SERVICES AND INFORMATION AND YOUR RELIANCE THEREON.</p>
			<p>dezignwall MAKES NO WARRANTY, REPRESENTATION OR GUARANTEE WITH RESPECT TO PRODUCTS AND SERVICES OFFERED BY THIRD-PARTY SELLERS ON THE WEBSITE, AND dezignwall SPECIFICALLY DISCLAIMS ANY WARRANTY, REPRESENTATION OR GUARANTEE WITH RESPECT TO THE QUALITY, SAFETY, LEGALITY OR OTHER CHARACTERISTICS OF SUCH PRODUCTS AND SERVICES, OR WITH RESPECT TO THE CONDUCT OF ANY THIRD-PARTY SELLER IN CONNECTION WITH SUCH OFFERS OR SALES.</p>
			<p><strong>Limitation of Liability</strong></p>
			<p>NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY OF ANY KIND, NEITHER dezignwall NOR ANY OF ITS LICENSORS, SPONSORS, AGENTS, SUCCESSORS, OR ASSIGNS, NOR OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, OR OTHER REPRESENTATIVES, ARE RESPONSIBLE OR LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES (INCLUDING WITHOUT LIMITATION ANY LOSS OF PROFITS, LOST SAVINGS, OR LOSS OF DATA) OR LIABILITIES UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY MANNER TO THE WEBSITE, INFORMATION, SERVICES AND/OR ANY LINKED WEBSITE, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES OR LIABILITIES. YOUR SOLE REMEDY WITH RESPECT TO THIS WEBSITE, THE INFORMATION, SERVICES, OR ANY LINKED WEBSITE IS TO STOP USING THE WEBSITE, SERVICE, OR LINKED WEBSITE, AS APPLICABLE. NEITHER dezignwall NOR ANY OF ITS LICENSORS, SPONSORS, AGENTS, SUCCESSORS, OR ASSIGNS, NOR OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, OR OTHER REPRESENTATIVES WILL HAVE ANY LIABILITY TO YOU FOR ANY DAMAGES, EXPENSES OR OTHER LIABILITY INCURRED BY YOU AS A RESULT OF (1) ANY INACCURACY, INCOMPLETENESS OR MISREPRESENTATION OF ANY INFORMATION, CONTENT, POSTINGS OR SUBMISSIONS PROVIDED OR POSTED ON THE WEBSITE BY THIRD PARTIES OR (2) YOUR HIRING OR ENGAGEMENT OF, OR ASSOCIATION WITH, ANY THIRD PARTY ADVERTISING OR OFFERING PRODUCTS OR SERVICES THROUGH THE WEBSITE.</p>
			<p><strong>Indemnification</strong></p>
			<p>You agree to fully indemnify, defend, and hold dezignwall, our licensors, suppliers, agents, successors, and assigns and our and their directors, officers, employees, consultants, and other representatives, harmless from and against any and all claims, damages, losses, costs (including reasonable attorneys' fees), and other expenses that arise directly or indirectly out of or from: (a) your breach of this Agreement, including but not limited to the Acceptable Use Policy; (b) any allegation that any materials you submit to us or transmit to the Website infringe or otherwise violate the copyright, patent, trademark, trade secret, or other intellectual property or other rights of any third party; (c) your activities in connection with the Website or other websites to which the Website is linked; and/or (d) your negligence or willful misconduct.</p>
			<p><strong>Jurisdictional Issues</strong></p>
			<p>dezignwall makes no representation that the Website operates (or is legally permitted to operate) in all geographic areas, or that the Information, Website, or Services are appropriate or available for use in other locations. Accessing the Website from territories where the Website or any content or functionality of the Website or portion thereof is illegal is expressly prohibited. If you choose to access the Website, you agree and acknowledge that you do so on your own initiative and at your own risk, and that you are solely responsible for compliance with all applicable laws.</p>
			<p><strong>Notice for California Users</strong></p>
			<p>Under California Civil Code Section 1789.3, California Website users are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 N. Market Blvd., Suite S-202, Sacramento, California 95834, or by telephone at (800) 952-5210.</p>
			<p><strong>Dispute Resolution/Governing Law</strong></p>
			<p>This Agreement shall be governed by and construed in accordance with the laws of the State of California, excluding that body of law relating to conflict of laws. The parties agree that any controversy or claim arising out of or relating to this Agreement, or the breach thereof, will be settled by binding arbitration in accordance with California Code of Civil Procedure Section 1280 et seq., and the then current rules and procedures of JAMS. The arbitration shall be a confidential proceeding, closed to the general public. The arbitration will take place in San Francisco, California and be conducted in the English language. The decision rendered by the arbitrator will be binding upon the parties hereto, and any judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction thereof. The parties consent to the jurisdiction of all federal and state courts in California. Venue will lie exclusively in San Francisco, California. For the sake of clarity, nothing in this paragraph shall affect dezignwall's ability to seek from a court injunctive or equitable relief at any time.</p>
			<p>If any arbitration or other proceeding is brought to enforce or interpret this Agreement or matters relating to it, the substantially prevailing party, as determined by the arbitrator's award, will be entitled to recover reasonable attorneys' fees and other costs and expenses incurred in such arbitration or proceeding from the other party, in addition to any other relief to which such prevailing party is entitled; provided that in no event will the arbitrator have the authority to award punitive damages.</p>
			<p><strong>Miscellaneous</strong></p>
			<p>If any provision of this Agreement is found to be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from this Agreement and shall not affect the validity and enforceability of any remaining provisions. This is the entire Agreement between you and us relating to the subject matter herein and supersedes any and all prior or contemporaneous written or oral agreements between you and us with respect to such subject matter. This Agreement may not be changed, waived or modified except by dezignwall as provided herein or otherwise by written instrument signed by dezignwall. Neither this Agreement nor any right, obligation, or remedy hereunder is assignable, transferable, delegatable, or sublicensable by you except with dezignwall's prior written consent, and any attempted assignment, transfer, delegation, or sublicense shall be null and void. dezignwall may assign, transfer, or delegate this Agreement or any right or obligation or remedy hereunder in its sole discretion. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. Any heading, caption, or section title contained in this Agreement is inserted only as a matter of convenience and in no way defines or explains any section or provision hereof.</p>
			<p><strong>This Website is Operated By<br></strong>dezignwall, Inc.<br>Effective January 9, 2016<br>Last modified as of January 9, 2016</p>
		</article>
	</div>
</div>